/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.MiembroData;
import controllers.ProyectoData;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import models.Miembro;
import models.Proyecto;
import static views.Gestion.desktop;
import static views.Gestion.vistaProyecto;

/**
 *
 * @author leo_t
 */
public class AdminProyecto extends javax.swing.JInternalFrame {

    private boolean ver = false;

    /**
     * Creates new form MiembrosViews
     */
    public AdminProyecto() {
        initComponents();
        jButtonActualizar.setEnabled(false);
        jButtonBorrar.setEnabled(false);
        jButtonGuardar.setEnabled(false);
        inicializarcombo();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboProyecto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jRadioActualizar = new javax.swing.JRadioButton();
        jRadioNuevo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextdescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioActivar = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextnombre1 = new javax.swing.JTextField();
        jRadioButtonnoactivos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextidentidad = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(854, 728));
        setMinimumSize(new java.awt.Dimension(854, 728));
        setPreferredSize(new java.awt.Dimension(854, 728));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jComboProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioActualizar.setText("Actualizar");
        jRadioActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioActualizarActionPerformed(evt);
            }
        });

        jRadioNuevo.setText("Nuevo");
        jRadioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNuevoActionPerformed(evt);
            }
        });

        jTextdescripcion.setColumns(20);
        jTextdescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextdescripcion);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Descripcion:");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estado");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        radioActivar.setText("Activar/Desactivar");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha:");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre:");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jRadioButtonnoactivos.setText("No activos");
        jRadioButtonnoactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonnoactivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioActualizar)
                                .addGap(90, 90, 90)
                                .addComponent(jRadioNuevo)
                                .addGap(69, 69, 69)
                                .addComponent(jRadioButtonnoactivos))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(radioActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioActualizar)
                    .addComponent(jRadioNuevo)
                    .addComponent(jRadioButtonnoactivos))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radioActivar))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administar Proyecto");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Sistema de Gestion", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextidentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextidentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void inicializarcombo() {
        ArrayList<Proyecto> proyectos = new ArrayList();
        ProyectoData proyectod = new ProyectoData();
        proyectos = proyectod.selectProyecto();
        for (Proyecto proyecto : proyectos) {
            jComboProyecto.addItem(proyecto);
        }
    }
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

    }//GEN-LAST:event_formInternalFrameClosing

    private void jRadioActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioActualizarActionPerformed
        // TODO add your handling code here:
        if (ver && jTextidentidad.getText() != "") {
            if (jRadioNuevo.isSelected()) {
                jRadioActualizar.setSelected(false);
            }
            if (!jRadioActualizar.isSelected()) {
                jTextdescripcion.setEditable(false);
                jTextidentidad.setEnabled(false);
                jDateChooser1.setEnabled(false);
                radioActivar.setEnabled(false);
                jButtonActualizar.setEnabled(false);
            } else {
                jTextdescripcion.setEditable(true);
                jTextidentidad.setEnabled(false);
                jTextnombre1.setEditable(true);
                jDateChooser1.setEnabled(true);
                radioActivar.setEnabled(true);
                jButtonActualizar.setEnabled(true);
                jButtonBorrar.setEnabled(false);
            }
        } else {
            jTextdescripcion.setEditable(false);
            jTextidentidad.setEnabled(false);
            jDateChooser1.setEnabled(false);
            jTextnombre1.setEditable(false);
            radioActivar.setEnabled(false);
            jButtonActualizar.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Para Actualizar en Necesario Presionar el boton Cargar");
        }
    }//GEN-LAST:event_jRadioActualizarActionPerformed

    private void jRadioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNuevoActionPerformed
        if (jRadioActualizar.isSelected()) {
            jRadioNuevo.setSelected(false);
        }
        if (!jRadioNuevo.isSelected()) {
            jTextdescripcion.setEditable(false);
            jTextidentidad.setEnabled(false);
            jDateChooser1.setEnabled(false);
            radioActivar.setEnabled(false);
            jButtonActualizar.setEnabled(false);
            jButtonGuardar.setEnabled(false);

        } else {
            jTextdescripcion.setEditable(true);
            jTextidentidad.setEnabled(false);
            jTextnombre1.setEditable(true);
            jDateChooser1.setEnabled(true);
            radioActivar.setEnabled(true);
            jButtonActualizar.setEnabled(false);
            jButtonGuardar.setEnabled(true);
            jButtonBorrar.setEnabled(false);
        }
        limpiar();
    }//GEN-LAST:event_jRadioNuevoActionPerformed

    private void limpiar() {
        jTextdescripcion.setText("");
        jTextidentidad.setText("");
        jDateChooser1.setDate(null);
        jTextnombre1.setText("");

    }

    private boolean validar() {
        if (!jTextnombre1.getText().equals("") && !jTextdescripcion.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        vistaProyecto = new ProyectoView();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        if (validar()) {
            Proyecto proyect = new Proyecto();
            ProyectoData proyectod = new ProyectoData();
            String var;
            int numeroInt = Integer.parseInt(jTextidentidad.getText());
            proyect.setId_proyecto(numeroInt);
            proyect.setNombre(jTextnombre1.getText());
            proyect.setDescripcion(jTextdescripcion.getText());
            proyect.setEstado(radioActivar.isSelected());
            java.time.LocalDate fechaInicioLocalDate = jDateChooser1.getCalendar().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            proyect.setFecha_inicio(fechaInicioLocalDate);
            proyectod.updateProyecto(proyect); // TODO add your handling code here:
            limpiar();
            jTextdescripcion.setEditable(false);
            jTextidentidad.setEnabled(false);
            jDateChooser1.setEnabled(false);
            jTextnombre1.setEditable(false);
            radioActivar.setEnabled(false);
            jButtonActualizar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Necesita llenar Los Campos");
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        Proyecto proyect = new Proyecto();
        ProyectoData proyectod = new ProyectoData();
        String var;
        int numeroInt = Integer.parseInt(jTextidentidad.getText());
        proyect.setId_proyecto(numeroInt);
        proyect.setNombre(jTextnombre1.getText());
        proyect.setDescripcion(jTextdescripcion.getText());
        proyect.setEstado(false);
        java.time.LocalDate fechaInicioLocalDate = jDateChooser1.getCalendar().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        proyect.setFecha_inicio(fechaInicioLocalDate);
        proyectod.updateProyecto(proyect);
        limpiar();
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private boolean validarfecha() {
        Calendar fechaActual = Calendar.getInstance();
        if (jDateChooser1.getCalendar() == null) {
            return false;
        }
        Calendar fechaSeleccionada = jDateChooser1.getCalendar();
        int añoActual = fechaActual.get(Calendar.YEAR);
        int mesActual = fechaActual.get(Calendar.MONTH);
        int diaActual = fechaActual.get(Calendar.DAY_OF_MONTH);
        int añoSeleccionado = fechaSeleccionada.get(Calendar.YEAR);
        int mesSeleccionado = fechaSeleccionada.get(Calendar.MONTH);
        int diaSeleccionado = fechaSeleccionada.get(Calendar.DAY_OF_MONTH);
        if (añoSeleccionado == añoActual && mesSeleccionado == mesActual && diaSeleccionado == diaActual) {
            return true;
        } else {
            return false;
        }
    }
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        Calendar fechaActual = Calendar.getInstance();
        if (validarfecha()) {
            if (validar()) {
                Proyecto proyect = new Proyecto();
                ProyectoData proyectod = new ProyectoData();
                String var;
                proyect.setNombre(jTextnombre1.getText());
                proyect.setDescripcion(jTextdescripcion.getText());
                proyect.setEstado(radioActivar.isSelected());
                java.time.LocalDate fechaInicioLocalDate = jDateChooser1.getCalendar().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                proyect.setFecha_inicio(fechaInicioLocalDate);
                proyectod.insertProyecto(proyect);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Necesita llenar Los Campos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por Favor seleccione fecha Actual");
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Proyecto proyecto1;
        proyecto1 = (Proyecto) jComboProyecto.getSelectedItem();
        jRadioActualizar.setSelected(false);
        jRadioNuevo.setSelected(false);
        jTextidentidad.setEnabled(false);
        String var;
        int i = proyecto1.getId_proyecto();
        var = "" + i;
        jTextidentidad.setText(var);
        jTextnombre1.setText(proyecto1.getNombre());
        jTextdescripcion.setText(proyecto1.getDescripcion());
        java.sql.Date fechaInicioSQL = java.sql.Date.valueOf(proyecto1.getFecha_inicio());
        jDateChooser1.setDate(fechaInicioSQL);
        radioActivar.setSelected(proyecto1.getEstado());
        jTextdescripcion.setEditable(false);
        jTextidentidad.setEnabled(false);
        jTextnombre1.setEditable(false);
        jDateChooser1.setEnabled(false);
        radioActivar.setEnabled(false);
        jButtonBorrar.setEnabled(true);
        jButtonActualizar.setEnabled(false);
        jButtonGuardar.setEnabled(false);
        ver = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonnoactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonnoactivosActionPerformed
        if (jRadioButtonnoactivos.isSelected()) {
            jComboProyecto.removeAllItems();
            ProyectoData proyec = new ProyectoData();
            ArrayList<Proyecto> proyectos = new ArrayList();
            proyectos = proyec.selectProyectoid0();
            for (int i = 0; i < proyectos.size(); i++) {
                jComboProyecto.addItem(proyectos.get(i));
            }
        } else {
            jComboProyecto.removeAllItems();
            inicializarcombo();
        }
    }//GEN-LAST:event_jRadioButtonnoactivosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<Proyecto> jComboProyecto;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioActualizar;
    private javax.swing.JRadioButton jRadioButtonnoactivos;
    private javax.swing.JRadioButton jRadioNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextdescripcion;
    private javax.swing.JLabel jTextidentidad;
    private javax.swing.JTextField jTextnombre1;
    private javax.swing.JRadioButton radioActivar;
    // End of variables declaration//GEN-END:variables
}
