/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.sun.awt.AWTUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author leo_t
 */
public class IniciarPrograma extends javax.swing.JFrame {

    /**
     * * CAMBIA USO DE BASE DATOS LOCAL O REMOTO **
     */
   public static final boolean LOCAL = false;
    Timer timer;
    ActionListener actionListener;
     Gestion gestion;
    AdminProyecto adminProyecto;
    ComentariosView comentarios;
    Enlace enlace;
    Equipovista equipo;
    MiembrosViews miembros;
    ModificarTareaView tarea;
    ProyectoView proyecto;
    int seleccion = 0;
    String claseCargada = "";
    /**
     * Creates new form IniciarPrograma
     */
    public IniciarPrograma() {
        actionListener = (ActionEvent ae) -> {
            seleccion += 10;
           if (Progreso.getValue() < 80) {
                Progreso.setValue(seleccion);
                cargar.setText("Cargando... " + claseCargada);
                cargarClases();
            } else {
                timer.stop();
                dispose();
                cargarClases();
                gestion.setVisible(true);
            }
        };
        initComponents();
        this.setSize(603, 526);
        this.setLocationRelativeTo(null);
        timer = new Timer(500, actionListener);
        AWTUtilities.setWindowOpaque(this, false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargar = new javax.swing.JLabel();
        Progreso = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        cargar.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        cargar.setForeground(new java.awt.Color(0, 0, 0));
        cargar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cargar.setToolTipText("");
        getContentPane().add(cargar);
        cargar.setBounds(140, 10, 340, 30);

        Progreso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progreso.setForeground(new java.awt.Color(255, 102, 51));
        Progreso.setBorderPainted(false);
        Progreso.setName(""); // NOI18N
        getContentPane().add(Progreso);
        Progreso.setBounds(100, 500, 460, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_proyecto/proyecto2.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 620, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new IniciarPrograma().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progreso;
    private javax.swing.JLabel cargar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
 public void cargarClases() {
        switch (seleccion) {
            case 10:
                gestion = new Gestion();
                claseCargada = "Gestion";
                break;
            case 20:
                adminProyecto = new AdminProyecto();
                claseCargada = "Proyectos";
                break;
            case 30:
                comentarios = new ComentariosView();
                claseCargada = "Comentarios";
                break;
            case 40:
                enlace = new Enlace();
                claseCargada = "Enlace";
                break;
            case 50:
                equipo = new Equipovista();
                claseCargada = "Equipos";
                break;
            case 60:
                miembros = new MiembrosViews();
                claseCargada = "Miembros";
                break;
            case 70:
                tarea = new ModificarTareaView();
                claseCargada = "Tareas";
                break;
            case 80:
                proyecto = new ProyectoView();
                claseCargada = "Menu";
                break;
            default:
                break;
        }
    }
}
